<?php
/**
 * Created by PhpStorm.
 * User: rubenmadila
 * Date: 2019-04-22
 * Time: 09:54
 */

?>
<div class="particle-cloud">
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-microphone-alt"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-guitar"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-drum"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-headphones"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-music"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-play"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-backward"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-pause-circle"></i>
    <i class="fas fa-pause-circle"></i>
</div>
